=== filecoin-project/filplus-tooling-backend-test/validationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Version": { "type": "number" },
    "ID": { "type": "string" },
    "Issue Number": { "type": "string" },
    "Client": {
      "type": "object",
      "properties": {
        "DataCap Applicant": { "type": "string" },
        "Data Owner Name": { "type": "string" },
        "Data Owner Country/Region": { "type": "string" },
        "Data Owner Industry": { "type": "string" },
        "Website": { "type": "string" },
        "Social Media Handle": { "type": "string" },
        "Social Media Type": { "type": "string" },
        "What is your role related to the dataset": { "type": "string" }
      },
      "required": ["DataCap Applicant", "Data Owner Name", "Data Owner Country/Region", "Data Owner Industry", "Website", "Social Media Handle", "Social Media Type", "What is your role related to the dataset"]
    },
    "Project": {
      "type": "object",
      "properties": {
        "Project Id": { "type": "string" },
        "Share a brief history of your project and organization": { "type": "string" },
        "Is this project associated with other projects/ecosystem stakeholders?": { "type": "string" },
        "Describe the data being stored onto Filecoin": { "type": "string" },
        "Where was the data currently stored in this dataset sourced from": { "type": "string" },
        "How do you plan to prepare the dataset": { "type": "string" },
        "Please share a sample of the data (a link to a file, an image, a table, etc., are good ways to do this.)": { "type": "string" },
        "Confirm that this is a public dataset that can be retrieved by anyone on the network (i.e., no specific permissions or access rights are required to view the data)": { "type": "string" },
        "What is the expected retrieval frequency for this data": { "type": "string" },
        "For how long do you plan to keep this dataset stored on Filecoin": { "type": "string" },
        "In which geographies do you plan on making storage deals": { "type": "string" },
        "How will you be distributing your data to storage providers": { "type": "string" },
        "Please list the provider IDs and location of the storage providers you will be working with. Note that it is a requirement to list a minimum of 5 unique provider IDs, and that your client address will be verified against this list in the future": { "type": "string" },
        "Can you confirm that you will follow the Fil+ guideline (Data owner should engage at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap)": { "type": "string" }
      },
      "required": [
        "Project Id",
        "Share a brief history of your project and organization",
        "Is this project associated with other projects/ecosystem stakeholders?",
        "Describe the data being stored onto Filecoin",
        "Where was the data currently stored in this dataset sourced from",
        "How do you plan to prepare the dataset",
        "Please share a sample of the data (a link to a file, an image, a table, etc., are good ways to do this.)",
        "Confirm that this is a public dataset that can be retrieved by anyone on the network (i.e., no specific permissions or access rights are required to view the data)",
        "What is the expected retrieval frequency for this data",
        "For how long do you plan to keep this dataset stored on Filecoin",
        "In which geographies do you plan on making storage deals",
        "How will you be distributing your data to storage providers",
        "Please list the provider IDs and location of the storage providers you will be working with. Note that it is a requirement to list a minimum of 5 unique provider IDs, and that your client address will be verified against this list in the future",
        "Can you confirm that you will follow the Fil+ guideline (Data owner should engage at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap)"
      ]
    },
    "Datacap": {
      "type": "object",
      "properties": {
        "Group": { "type": "string" },
        "Data Type": { "type": "string" },
        "Total amount of DataCap being requested": { "type": "string" },
        "Expected size of single dataset (one copy)": { "type": "string" },
        "Number of Replicas to Store": { "type": "number" },
        "Weekly allocation of DataCap requested": { "type": "string" },
        "Custom Multisig": { "type": "string" },
        "Identifier": { "type": "string" }
      },
      "required": ["Group", "Data Type", "Total amount of DataCap being requested", "Expected size of single dataset (one copy)", "Number of Replicas to Store", "Weekly allocation of DataCap requested"]
    },
    "Lifecycle": {
      "type": "object",
      "properties": {
        "State": { "type": "string" },
        "Validated At": { "type": "string" },
        "Validated By": { "type": "string" },
        "Active": { "type": "boolean" },
        "Updated At": { "type": "string" },
        "Active Request ID": { "type": "string" },
        "On Chain Address": { "type": "string" },
        "Multisig Address": { "type": "string" }
      },
      "required": ["State", "Validated At", "Validated By", "Active", "Updated At", "Active Request ID", "On Chain Address", "Multisig Address"]
    },
    "Allocation Requests": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ID": { "type": "string" },
          "Request Type": { "type": "string" },
          "Created At": { "type": "string" },
          "Updated At": { "type": "string" },
          "Active": { "type": "boolean" },
          "Allocation Amount": { "type": "string" },
          "Signers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Github Username": { "type": "string" },
                "Signing Address": { "type": "string" },
                "Created At": { "type": "string" },
                "Message CID": { "type": "string" }
              },
              "required": ["Github Username", "Signing Address", "Created At", "Message CID"]
            }
          }
        },
        "required": ["ID", "Request Type", "Created At", "Updated At", "Active", "Allocation Amount", "Signers"]
      }
    }
  },
  "required": ["Version", "ID", "Issue Number", "Client", "Project", "Datacap", "Lifecycle", "Allocation Requests"],
  "additionalProperties": false
}

=== filecoin-project/filplus-tooling-backend-test/applications/f410f424a6foarbjmjdv4p4p6jtlwgxfev4s2dqeelry.json
{
  "Version": 1,
  "ID": "f410f424a6foarbjmjdv4p4p6jtlwgxfev4s2dqeelry",
  "Issue Number": "771",
  "Client": {
    "DataCap Applicant": "applicant",
    "Data Owner Name": "Charly Owner Name",
    "Data Owner Country/Region": "Spain",
    "Data Owner Industry": "Arts & Recreation",
    "Website": "keyko.io",
    "Social Media Handle": "sm handle",
    "Social Media Type": "Twitter",
    "What is your role related to the dataset": "Dataset Owner"
  },
  "Project": {
    "Project Id": "111",
    "Share a brief history of your project and organization": "Sample of project details",
    "Is this project associated with other projects/ecosystem stakeholders?": "Yes",
    "Describe the data being stored onto Filecoin": "Use case details storage",
    "Where was the data currently stored in this dataset sourced from": "Other",
    "How do you plan to prepare the dataset": "data will be prepared",
    "Please share a sample of the data (a link to a file, an image, a table, etc., are good ways to do this.)": "",
    "Confirm that this is a public dataset that can be retrieved by anyone on the network (i.e., no specific permissions or access rights are required to view the data)": "",
    "What is the expected retrieval frequency for this data": "Weekly",
    "For how long do you plan to keep this dataset stored on Filecoin": "1.5 to 2 years",
    "In which geographies do you plan on making storage deals": "Asia other than Greater China, South America",
    "How will you be distributing your data to storage providers": "HTTP or FTP server, Venus built-in data transfer",
    "Please list the provider IDs and location of the storage providers you will be working with. Note that it is a requirement to list a minimum of 5 unique provider IDs, and that your client address will be verified against this list in the future": "",
    "Can you confirm that you will follow the Fil+ guideline (Data owner should engage at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap)": ""
  },
  "Datacap": {
    "Group": "ldn-v3",
    "Data Type": "Slingshot",
    "Total amount of DataCap being requested": "2 PiB",
    "Expected size of single dataset (one copy)": "1 TiB",
    "Number of Replicas to Store": 4,
    "Weekly allocation of DataCap requested": "1 PiB"
  },
  "Lifecycle": {
    "State": "Submitted",
    "Validated At": "",
    "Validated By": "",
    "Active": true,
    "Updated At": "2023-12-14 08:39:54.109518698 UTC",
    "Active Request ID": "",
    "On Chain Address": "f410f424a6foarbjmjdv4p4p6jtlwgxfev4s2dqeelry",
    "Multisig Address": "false"
  },
  "Allocation Requests": []
}

=== filecoin-project/filplus-tooling-backend-test/applications/f1ys5m675da4ao4vwefbewtyafuw3zhgemya6jnky.json
{
  "Version": 1,
  "ID": "f1ys5m675da4ao4vwefbewtyafuw3zhgemya6jnky",
  "Issue Number": "769",
  "Client": {
    "DataCap Applicant": "",
    "Data Owner Name": "charly",
    "Data Owner Country/Region": "Spain",
    "Data Owner Industry": "Education & Training",
    "Website": "keyko.io",
    "Social Media Handle": "sm",
    "Social Media Type": "Facebook",
    "What is your role related to the dataset": "Data Preparer"
  },
  "Project": {
    "Project Id": "111",
    "Share a brief history of your project and organization": "history",
    "Is this project associated with other projects/ecosystem stakeholders?": "Yes",
    "Describe the data being stored onto Filecoin": "data stored onto filecoin",
    "Where was the data currently stored in this dataset sourced from": "Other",
    "How do you plan to prepare the dataset": "preparing data",
    "Please share a sample of the data (a link to a file, an image, a table, etc., are good ways to do this.)": "",
    "Confirm that this is a public dataset that can be retrieved by anyone on the network (i.e., no specific permissions or access rights are required to view the data)": "",
    "What is the expected retrieval frequency for this data": "Weekly",
    "For how long do you plan to keep this dataset stored on Filecoin": "1.5 to 2 years",
    "In which geographies do you plan on making storage deals": "Africa, South America",
    "How will you be distributing your data to storage providers": "HTTP or FTP server, Lotus built-in data transfer",
    "Please list the provider IDs and location of the storage providers you will be working with. Note that it is a requirement to list a minimum of 5 unique provider IDs, and that your client address will be verified against this list in the future": "",
    "Can you confirm that you will follow the Fil+ guideline (Data owner should engage at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap)": ""
  },
  "Datacap": {
    "Group": "ldn-v3",
    "Data Type": "Slingshot",
    "Total amount of DataCap being requested": "2 PiB",
    "Expected size of single dataset (one copy)": "100 GiB",
    "Number of Replicas to Store": 0,
    "Weekly allocation of DataCap requested": "1 "
  },
  "Lifecycle": {
    "State": "Submitted",
    "Validated At": "",
    "Validated By": "",
    "Active": true,
    "Updated At": "2023-12-14 08:00:34.776052653 UTC",
    "Active Request ID": "",
    "On Chain Address": "f1ys5m675da4ao4vwefbewtyafuw3zhgemya6jnky",
    "Multisig Address": "false"
  },
  "Allocation Requests": []
}
